#!/bin/tcsh
#
# kill and restart weather_srv.pl
# weather_srv.pl is a server that takes socket commands to
# determine the dome status of the La Silla domes
#
slay weather_srv.pl
cd /home/observer/palomar/weather_srv
echo `date` >>& weather_srv.out
echo "restarting weather server" >> weather_srv.out
weather_srv.pl >>& weather_srv.out &
sleep 1
echo "s" | weather_client.pl
#
